
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, -1, ed);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, nt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, nt2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, nt3);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, wt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, br);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, gm);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, an);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, pv);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, vs1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, vs2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, vp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, vp2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (22, 0, np1);