
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, -1, np1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, mp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, np2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, wp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, wp2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, ga);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, av);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, aw);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, ai);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, vs1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, ns1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, ns2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, nt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (9, 0, nt2);