
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, -1, vp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, -1, ai);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, mp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, vp2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, vp3);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, np1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, gm);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, an);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, ad);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, ad2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, pv);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, ss1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, dt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, nt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (27, 0, sg1);