
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, np1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, np2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, np3);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, wp1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, gm);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, hr);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, av);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, ai);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, pw);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, vs1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, vs2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, wt1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, wt2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, gg);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, sg1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH) VALUES (3, 0, sg2);