INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (12, 1, 185, 55, 3, 8, 7, 7, 10, 14, 177);
INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (12, 50, 3565, 60, 19, 37, 36, 25, 37, 47, 626);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 1);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 47, 2);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 47, 3);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 4);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 20);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 21);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 22);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 32);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 42, 33);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 35);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 36);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 37);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 38);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 47, 41);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 47, 43);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 47, 45);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 56);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (12, 59, 58);