INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (7, 1, 132, 60, 11, 9, 4, 2, 2, 1, 43);
INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (7, 50, 3029, 76, 51, 57, 29, 24, 23, 7, 498);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 12, 6);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 7);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 12, 9);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 13);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 14);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 15);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 20);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 21);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 12, 24);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 25);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 26);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 35);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 36);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 39);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 38, 53);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (7, 30, 54);