INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (9, 1, 115, 60, 6, 9, 9, 7, 7, 1, 47);
INSERT INTO BB_PLAYER_LVL_STATS(PLAYER_ID, LEVEL, HP, SPD, SHOT, ENDUR, PASS, ATK, BLK, CAT, SALARY) 
VALUES (9, 50, 3096, 79, 28, 51, 55, 32, 29, 11, 485);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 24, 4);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 24, 8);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 22, 15);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 22, 16);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 44, 21);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 44, 22);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 44, 23);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 44, 24);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 24, 30);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 22, 31);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 24, 48);
INSERT INTO BB_KEY_TECH_UNLOCKS (PLAYER_ID, KEY_TECH, LEARNABLE_TECH)
VALUES (9, 22, 57);