CREATE TABLE IDENTITY(
 IDENTIFIER INT AUTO_INCREMENT PRIMARY KEY,
 RACING_IDENTIFIER INT
);

CREATE TABLE RACING_GAME(
 RACING_IDENTIFIER INT AUTO_INCREMENT PRIMARY KEY,
 AVAILABLE_CASH DECIMAL(11,2) NOT NULL,
 RACING_CLASS VARCHAR(1) NOT NULL
);

CREATE TABLE RACECARS(
 CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
 RACING_CLASS VARCHAR(1) NOT NULL,
 TOP_SPEED INT NOT NULL,
 ACCELERATION DECIMAL(5, 2) NOT NULL,
 RELIABILITY DECIMAL(2,2) NOT NULL,
 LAP_EFFICIENCY DECIMAL(2,2) NOT NULL,
 MODEL VARCHAR(30) NOT NULL,
 PRICE INT NOT NULL
);

CREATE TABLE UPGRADES(
 UPGRADE_ID INT AUTO_INCREMENT PRIMARY KEY,
 TOP_SPEED_MOD INT,
 ACCELERATION_MOD DECIMAL(5, 2),
 RELIABILITY_MOD DECIMAL(2,2),
 LAP_EFFICIENCY_MOD DECIMAL(2,2),
 PRICE INT NOT NULL,
 RACING_CLASS VARCHAR(1) NOT NULL
);

CREATE TABLE USER_RACECARS(
 USER_RACECAR_ID INT AUTO_INCREMENT PRIMARY KEY,
 RACING_IDENTIFIER INT NOT NULL,
 CAR_ID INT NOT NULL
);



CREATE TABLE USER_RACECAR_UPGRADES(
 USER_RACECAR_ID INT NOT NULL,
 UPGRADE_ID INT NOT NULL
);