INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('E', 100, 10.00, 0.70, 0.50, 'red_sedan.png', 500);



INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('D', 120, 15.00, 0.70, 0.50, 'red_fer.png', 2000);



INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('C', 150, 25.00, 0.70, 0.50, 'silver_chevvy.png', 10000);



INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('B', 200, 35.00, 0.70, 0.50, 'red_fer.png', 20000);



INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('A', 250, 50.00, 0.70, 0.50, 'silver_audi2.png', 50000);



INSERT INTO RACECARS(RACING_CLASS, TOP_SPEED, ACCELERATION, RELIABILITY, LAP_EFFICIENCY, MODEL, PRICE) 
VALUES ('S', 350, 75.00, 0.70, 0.50, 'black_lambo.png', 150000);

INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (20, 100, 'E');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (4, 100, 'E');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 100, 'E');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 100, 'E');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (10, 2, 100, 'E');


INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (25, 500, 'D');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (5, 500, 'D');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 500, 'D');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 500, 'D');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (12, 3, 500, 'D');


INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (30, 2000, 'C');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (6, 2000, 'C');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 2000, 'C');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 2000, 'C');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (15, 3, 2000, 'C');


INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (35, 5000, 'B');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (7, 5000, 'B');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 5000, 'B');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 5000, 'B');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (17, 4, 5000, 'B');


INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (40, 15000, 'A');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (8, 15000, 'A');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 15000, 'A');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 15000, 'A');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (20, 4, 15000, 'A');


INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (45, 30000, 'S');

INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (9, 30000, 'S');

INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.1, 30000, 'S');

INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.07, 30000, 'S');

INSERT INTO UPGRADES (TOP_SPEED_MOD, ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (22, 5, 30000, 'S');