update RACECARS set MODEL='volkswagen_beetle.png', NAME='Volkswagen Beetle', TOP_SPEED=95, ACCELERATION=14, RELIABILITY=0.35, LAP_EFFICIENCY=.4, PRICE=500, RACING_CLASS='E' where CAR_ID=1;
update RACECARS set MODEL='grand_cherokee.png', NAME='Jeep Grand Cherokee', TOP_SPEED=120, ACCELERATION=10, RELIABILITY=0.45, LAP_EFFICIENCY=.35, PRICE=1000, RACING_CLASS='E' where CAR_ID=7;
update RACECARS set MODEL='fiat_500.png', NAME='Fiat 500', TOP_SPEED=90, ACCELERATION=14, RELIABILITY=0.40, LAP_EFFICIENCY=0.4, PRICE=600, RACING_CLASS='E' where CAR_ID=13;
update RACECARS set MODEL='chrysler_200.png', NAME='Chrysler 200', TOP_SPEED=110, ACCELERATION=13, RELIABILITY=0.35, LAP_EFFICIENCY=.35, PRICE=800, RACING_CLASS='E' where CAR_ID=19;
update RACECARS set MODEL='kia_sorento.png', NAME='Kia Sorento', TOP_SPEED=110, ACCELERATION=12, RELIABILITY=0.35, LAP_EFFICIENCY=.3, PRICE=600, RACING_CLASS='E' where CAR_ID=25;

update RACECARS set MODEL='acura_tsx.png', NAME='Acura TSX', TOP_SPEED=140, ACCELERATION=23, RELIABILITY=0.45, LAP_EFFICIENCY=.35, PRICE=2500, RACING_CLASS='D' where CAR_ID=2;
update RACECARS set MODEL='honda_accord.png', NAME='Honda Accord', TOP_SPEED=135, ACCELERATION=25, RELIABILITY=0.40, LAP_EFFICIENCY=.35, PRICE=2200, RACING_CLASS='D' where CAR_ID=8;
update RACECARS set MODEL='buick_regal.png', NAME='Buick Regal', TOP_SPEED=150, ACCELERATION=17, RELIABILITY=0.5, LAP_EFFICIENCY=0.4, PRICE=1800, RACING_CLASS='D' where CAR_ID=14;
update RACECARS set MODEL='nissan_altima.png', NAME='Nissan Altima', TOP_SPEED=150, ACCELERATION=20, RELIABILITY=0.35, LAP_EFFICIENCY=.35, PRICE=2300, RACING_CLASS='D' where CAR_ID=20;
update RACECARS set MODEL='renault_twingo.png', NAME='Renault Twingo', TOP_SPEED=120, ACCELERATION=21, RELIABILITY=0.45, LAP_EFFICIENCY=.4, PRICE=2000, RACING_CLASS='D' where CAR_ID=26;
update RACECARS set MODEL='toyota_corolla.png', NAME='Toyota Corolla', TOP_SPEED=125, ACCELERATION=20, RELIABILITY=0.4, LAP_EFFICIENCY=.35, PRICE=1900, RACING_CLASS='D' where CAR_ID=31;
 
update RACECARS set MODEL='dodge_challenger.png', NAME='Dodge Challenger', TOP_SPEED=180, ACCELERATION=21, RELIABILITY=0.4, LAP_EFFICIENCY=.35, PRICE=12500, RACING_CLASS='C' where CAR_ID=3;
update RACECARS set MODEL='mustang_boss.png', NAME='Ford Mustang Boss', TOP_SPEED=160, ACCELERATION=27, RELIABILITY=0.4, LAP_EFFICIENCY=.3, PRICE=11000, RACING_CLASS='C' where CAR_ID=9;
update RACECARS set MODEL='infiniti_q50.png', NAME='Infiniti Q50', TOP_SPEED=155, ACCELERATION=26, RELIABILITY=0.40, LAP_EFFICIENCY=0.35, PRICE=9000, RACING_CLASS='C' where CAR_ID=15;
update RACECARS set MODEL='lincoln_mks.png', NAME='Lincoln MKS', TOP_SPEED=170, ACCELERATION=22, RELIABILITY=0.42, LAP_EFFICIENCY=.4, PRICE=11000, RACING_CLASS='C' where CAR_ID=21;
update RACECARS set MODEL='mazda_miata.png', NAME='Mazda Miata', TOP_SPEED=145, ACCELERATION=24, RELIABILITY=0.48, LAP_EFFICIENCY=.45, PRICE=10500, RACING_CLASS='C' where CAR_ID=27;
update RACECARS set MODEL='mitsubishi_eclipse.png', NAME='Mitsubishi Eclipse', TOP_SPEED=140, ACCELERATION=28, RELIABILITY=0.45, LAP_EFFICIENCY=.35, PRICE=9500, RACING_CLASS='C' where CAR_ID=32;
update RACECARS set MODEL='tesla_roadster.png', NAME='Tesla Roadster', TOP_SPEED=150, ACCELERATION=27, RELIABILITY=0.47, LAP_EFFICIENCY=.45, PRICE=12000, RACING_CLASS='C' where CAR_ID=33;

update RACECARS set MODEL='benz_f800.png', NAME='Mercedez Benz F800', TOP_SPEED=165, ACCELERATION=34, RELIABILITY=0.5, LAP_EFFICIENCY=.4, PRICE=22500, RACING_CLASS='B' where CAR_ID=4;
update RACECARS set MODEL='BMW_I8.png', NAME='BMW I8', TOP_SPEED=170, ACCELERATION=33, RELIABILITY=0.5, LAP_EFFICIENCY=.41, PRICE=25000, RACING_CLASS='B' where CAR_ID=10;
update RACECARS set MODEL='jaguar_f_type.png', NAME='Jaguar F-Type', TOP_SPEED=185, ACCELERATION=30, RELIABILITY=0.45, LAP_EFFICIENCY=0.4, PRICE=21000, RACING_CLASS='B' where CAR_ID=16;
update RACECARS set MODEL='lotus_esprit.png', NAME='Lotus Esprit', TOP_SPEED=180, ACCELERATION=30, RELIABILITY=0.43, LAP_EFFICIENCY=.38, PRICE=19500, RACING_CLASS='B' where CAR_ID=22;
update RACECARS set MODEL='maybach_62.png', NAME='Maybach 62', TOP_SPEED=182, ACCELERATION=25, RELIABILITY=0.55, LAP_EFFICIENCY=.4, PRICE=20000, RACING_CLASS='B' where CAR_ID=28;
update RACECARS set MODEL='spyker_c8_aileron.png', NAME='Spyker C8 Aileron', TOP_SPEED=200, ACCELERATION=32, RELIABILITY=0.4, LAP_EFFICIENCY=.45, PRICE=23500, RACING_CLASS='B' where CAR_ID=34;
update RACECARS set MODEL='stingray.png', NAME='Corvette Stingray', TOP_SPEED=192, ACCELERATION=31, RELIABILITY=0.55, LAP_EFFICIENCY=.42, PRICE=24500, RACING_CLASS='B' where CAR_ID=35;

update RACECARS set MODEL='amV8_vantage.png', NAME='Aston Martin V8 Vantage', TOP_SPEED=195, ACCELERATION=36, RELIABILITY=0.55, LAP_EFFICIENCY=.4, PRICE=50000, RACING_CLASS='A' where CAR_ID=5;
update RACECARS set MODEL='audi_r8.png', NAME='Audi R8', TOP_SPEED=204, ACCELERATION=37, RELIABILITY=0.45, LAP_EFFICIENCY=.35, PRICE=55000, RACING_CLASS='A' where CAR_ID=11;
update RACECARS set MODEL='bentley_continental.png', NAME='Bentley Continental GTC', TOP_SPEED=210, ACCELERATION=32, RELIABILITY=0.6, LAP_EFFICIENCY=0.42, PRICE=62000, RACING_CLASS='A' where CAR_ID=17;
update RACECARS set MODEL='lambo_murcielago.png', NAME='Lamborghini Murcielago', TOP_SPEED=215, ACCELERATION=39, RELIABILITY=0.4, LAP_EFFICIENCY=.37, PRICE=49000, RACING_CLASS='A' where CAR_ID=23;
update RACECARS set MODEL='lexus_lfa.png', NAME='Lexus LFA', TOP_SPEED=207, ACCELERATION=37, RELIABILITY=0.5, LAP_EFFICIENCY=.41, PRICE=55500, RACING_CLASS='A' where CAR_ID=29;
update RACECARS set MODEL='maserati_MC12.png', NAME='Maserati MC12', TOP_SPEED=210, ACCELERATION=38, RELIABILITY=0.45, LAP_EFFICIENCY=.39, PRICE=48500, RACING_CLASS='A' where CAR_ID=36;
update RACECARS set MODEL='pagani_zonda.png', NAME='Pagani Zonda Cinque', TOP_SPEED=213, ACCELERATION=35, RELIABILITY=0.48, LAP_EFFICIENCY=.41, PRICE=52000, RACING_CLASS='A' where CAR_ID=37;
update RACECARS set MODEL='porsche_911.png', NAME='Porsche 911', TOP_SPEED=198, ACCELERATION=36, RELIABILITY=0.53, LAP_EFFICIENCY=.42, PRICE=47500, RACING_CLASS='A' where CAR_ID=38;
update RACECARS set MODEL='rolls_royce_jonckheere.png', NAME='Rolls Royce Jonckheere Aerodynamic', TOP_SPEED=220, ACCELERATION=31, RELIABILITY=0.5, LAP_EFFICIENCY=.35, PRICE=52500, RACING_CLASS='A' where CAR_ID=39;

update RACECARS set MODEL='bugatti_veyron.png', NAME='Bugatti Veyron', TOP_SPEED=250, ACCELERATION=45, RELIABILITY=0.50, LAP_EFFICIENCY=.4, PRICE=175000, RACING_CLASS='S' where CAR_ID=6;
update RACECARS set MODEL='caparo_t1.png', NAME='Caparo T1', TOP_SPEED=210, ACCELERATION=50, RELIABILITY=0.55, LAP_EFFICIENCY=.35, PRICE=155000, RACING_CLASS='S' where CAR_ID=12;
update RACECARS set MODEL='koenigsegg_CCX.png', NAME='Koenigsegg CCX', TOP_SPEED=240, ACCELERATION=42, RELIABILITY=0.6, LAP_EFFICIENCY=0.42, PRICE=160000, RACING_CLASS='S' where CAR_ID=18;
update RACECARS set MODEL='laferrari.png', NAME='Ferrari Laferrary', TOP_SPEED=225, ACCELERATION=47, RELIABILITY=0.4, LAP_EFFICIENCY=.5, PRICE=180000, RACING_CLASS='S' where CAR_ID=24;
update RACECARS set MODEL='mclaren_p1.png', NAME='McLaren P1', TOP_SPEED=225, ACCELERATION=45, RELIABILITY=0.5, LAP_EFFICIENCY=.41, PRICE=135000, RACING_CLASS='S' where CAR_ID=30;
update RACECARS set MODEL='pagani_huayra.png', NAME='Pagani Huayra', TOP_SPEED=230, ACCELERATION=44, RELIABILITY=0.45, LAP_EFFICIENCY=.39, PRICE=148500, RACING_CLASS='S' where CAR_ID=40;
update RACECARS set MODEL='peugeot_onyx.png', NAME='Peugeot Onyx', TOP_SPEED=235, ACCELERATION=47, RELIABILITY=0.48, LAP_EFFICIENCY=.41, PRICE=152000, RACING_CLASS='S' where CAR_ID=41;
update RACECARS set MODEL='porsche_918.png', NAME='Porsche 918', TOP_SPEED=220, ACCELERATION=46, RELIABILITY=0.625, LAP_EFFICIENCY=.42, PRICE=147500, RACING_CLASS='S' where CAR_ID=42;
update RACECARS set MODEL='saab_PhoeniX.png', NAME='Saab PhoeniX', TOP_SPEED=224, ACCELERATION=43, RELIABILITY=0.6, LAP_EFFICIENCY=.45, PRICE=158500, RACING_CLASS='S' where CAR_ID=43;
update RACECARS set MODEL='saleen_s7.png', NAME='Saleen S7', TOP_SPEED=240, ACCELERATION=48, RELIABILITY=0.45, LAP_EFFICIENCY=.35, PRICE=147500, RACING_CLASS='S' where CAR_ID=44;

update RACECARS set MODEL='egoista.png', NAME='Lamborghini Egoista', TOP_SPEED=310, ACCELERATION=70, RELIABILITY=0.625, LAP_EFFICIENCY=.6, PRICE=275000, RACING_CLASS='SS' where CAR_ID=45;
update RACECARS set MODEL='hennessy_venom.png', NAME='Hennessy Venom GT', TOP_SPEED=320, ACCELERATION=60, RELIABILITY=0.7, LAP_EFFICIENCY=.6, PRICE=265000, RACING_CLASS='SS' where CAR_ID=46;
update RACECARS set MODEL='koenigsegg_one_1.png', NAME='Koenigsegg One:1', TOP_SPEED=290, ACCELERATION=65, RELIABILITY=0.75, LAP_EFFICIENCY=.65, PRICE=245000, RACING_CLASS='SS' where CAR_ID=47;

