create table BATTLESHIP_GAME(GAME_ID INT AUTO_INCREMENT PRIMARY KEY, STATUS VARCHAR(5) DEFAULT '1TURN', USER1 INT NOT NULL, USER2 INT NOT NULL);

create table BATTLESHIP_BOARD(GAME_ID INT NOT NULL, IDENTIFIER INT NOT NULL, CARRIER_LOC VARCHAR(3) NOT NULL, CARRIER_VERT BOOL NOT NULL,  BATTLESHIP_LOC VARCHAR(3) NOT NULL, BATTLESHIP_VERT BOOL NOT NULL, DESTROYER_LOC VARCHAR(3) NOT NULL, DESTROYER_VERT BOOL NOT NULL, SUBMARINE_LOC VARCHAR(3) NOT NULL, SUBMARINE_VERT BOOL NOT NULL, PATROL_LOC VARCHAR(3) NOT NULL, PATROL_VERT BOOL NOT NULL);

create table BATTLESHIP_MOVES(GAME_ID INT NOT NULL, IDENTIFIER INT NOT NULL, LOC VARCHAR(3) NOT NULL, STATUS VARCHAR(14) NOT NULL);