
INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (10, 100, 'E');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (2, 100, 'E');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.025, 100, 'E');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.02, 100, 'E');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (10, 500, 'D');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (2, 500, 'D');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.025, 500, 'D');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.02, 500, 'D');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (15, 2000, 'C');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (3, 2000, 'C');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.038, 2000, 'C');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.03, 2000, 'C');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (20, 5000, 'B');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (4, 5000, 'B');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.05, 5000, 'B');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.04, 5000, 'B');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (25, 15000, 'A');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (5, 15000, 'A');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.063, 15000, 'A');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.05, 15000, 'A');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (30, 30000, 'S');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (6, 30000, 'S');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.075, 30000, 'S');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.06, 30000, 'S');



INSERT INTO UPGRADES (TOP_SPEED_MOD, PRICE, RACING_CLASS) VALUES (30, 30000, 'SS');


INSERT INTO UPGRADES (ACCELERATION_MOD, PRICE, RACING_CLASS) VALUES (6, 30000, 'SS');


INSERT INTO UPGRADES (RELIABILITY_MOD, PRICE, RACING_CLASS) VALUES (.075, 30000, 'SS');


INSERT INTO UPGRADES (LAP_EFFICIENCY_MOD, PRICE, RACING_CLASS) VALUES (.06, 30000, 'SS');