CREATE TABLE BB_INFO(
 GAME_ID INT PRIMARY KEY,
 USER_ID INT NOT NULL,
 OPPONENT_1 INT NOT NULL,
 OPPONENT_2 INT NOT NULL,
 OPPONENT_3 INT NOT NULL,
 OPPONENT_4 INT NOT NULL,
 OPPONENT_5 INT NOT NULL,
 OPPONENT_6 INT NOT NULL,
 OPPONENT_7 INT NOT NULL,
 WINS INT,
 LOSSES INT,
 GOALS INT,
 GOALS_AGAINST INT
);

CREATE TABLE BB_LEAGUE(
 LEAGUE_ID INT AUTO_INCREMENT PRIMARY KEY,
 GAME_ID INT NOT NULL,
 WEEKS_COMPLETE INT,
 DIV_OPP1 INT NOT NULL,
 DIV_OPP2 INT NOT NULL,
 DIV_OPP3 INT NOT NULL
);

CREATE TABLE BB_LEAGUE_GAMES(
 LEAGUE_GAME_ID INT AUTO_INCREMENT PRIMARY KEY, 
 LEAGUE_ID INT NOT NULL,
 WEEK INT NOT NULL,
 TEAM_1 INT NOT NULL,
 TEAM_2 INT NOT NULL,
 SCORE_1 INT,
 SCORE_2 INT
);

CREATE TABLE BB_LEAGUE_GAME_STATS(
 LEAGUE_GAME_ID INT NOT NULL,
 PLAYER_ID INT NOT NULL,
 GOALS INT,
 SHOTS INT,
 ASSISTS INT,
 GOALS_AGAINST INT,
 SHOTS_AGAINST INT,
 TACKLES INT,
 BLOCKS INT,
 BREAKS INT,
 TURNOVERS INT
); 

CREATE TABLE BB_PLAYERS(
 PLAYER_ID INT NOT NULL,
 GAME_ID INT NOT NULL,
 NAME VARCHAR(30) NOT NULL,
 LEVEL INT NOT NULL,
 NEXT_EXP INT NOT NULL,
 SPD INT NOT NULL,
 ENDUR INT NOT NULL,
 HP INT NOT NULL,
 ATK INT NOT NULL,
 PASS INT NOT NULL,
 SHOT INT NOT NULL,
 BLK INT NOT NULL,
 CAT INT NOT NULL,
 CURR_TEAM INT NOT NULL,
 SALARY INT,
 CONTRACT_LENGTH INT,
 TECH1 INT,
 TECH2 INT,
 TECH3 INT,
 TECH4 INT,
 TECH5 INT,
 KEYTECH1 INT NOT NULL,
 KEYTECH2 INT NOT NULL,
 KEYTECH3 INT NOT NULL,
 PRIMARY KEY(PLAYER_ID, GAME_ID)
);

CREATE TABLE BB_TEAM(
 TEAM_ID INT AUTO_INCREMENT PRIMARY KEY,
 GAME_ID INT,
 TEAM_NAME VARCHAR(30) NOT NULL,
 LWING INT NOT NULL,
 RWING INT NOT NULL,
 MID INT NOT NULL,
 LBACK INT NOT NULL,
 RBACK INT NOT NULL,
 KEEPER INT NOT NULL,
 BENCH1 INT,
 BENCH2 INT,
 BENCH3 INT,
 AVAILABLE_CASH INT NOT NULL
);