ALTER TABLE BB_PLAYERS ADD MODEL VARCHAR(20);
ALTER TABLE BB_LEAGUE_GAMES ADD HALVES_COMPLETE INT;
UPDATE BB_PLAYERS SET MODEL='stormtrooper20.dae';
UPDATE BB_LEAGUE_GAMES SET HALVES_COMPLETE=0;

INSERT INTO IDENTITY (USERNAME) VALUES ('JUNIT');


CREATE TABLE BB_EXP_LVL_LOOKUP(
 LEVEL INT NOT NULL PRIMARY KEY,
 EXP INT NOT NULL
);


CREATE TABLE BB_PLAYER_LVL_STATS(
 PLAYER_ID INT NOT NULL,
 LEVEL INT NOT NULL,
 SPD INT NOT NULL,
 ENDUR INT NOT NULL,
 HP INT NOT NULL,
 ATK INT NOT NULL,
 PASS INT NOT NULL,
 SHOT INT NOT NULL,
 BLK INT NOT NULL,
 CAT INT NOT NULL,
 PRIMARY KEY(PLAYER_ID, LEVEL)
);

