DELIMITER $$

DROP PROCEDURE IF EXISTS `RESET_BLITZBALL_GAME`$$ 
 
CREATE PROCEDURE RESET_BLITZBALL_GAME(p_game_id INT) 
    NOT DETERMINISTIC
BEGIN
	DELETE FROM BB_LEAGUE_GAME_STATS WHERE LEAGUE_GAME_ID IN (SELECT LEAGUE_GAME_ID FROM BB_LEAGUE_GAMES WHERE LEAGUE_ID IN (SELECT LEAGUE_ID FROM BB_LEAGUE WHERE GAME_ID=p_game_id));
	DELETE FROM BB_LEAGUE_GAMES WHERE LEAGUE_ID IN (SELECT LEAGUE_ID FROM BB_LEAGUE WHERE GAME_ID=p_game_id);
	DELETE FROM BB_LEAGUE WHERE GAME_ID=p_game_id;
	DELETE FROM BB_PLAYER_TECHS WHERE GAME_ID=p_game_id;
	DELETE FROM BB_PLAYERS WHERE GAME_ID=p_game_id;
	DELETE FROM BB_TEAM WHERE GAME_ID=p_game_id;
	UPDATE BB_INFO SET GAME_ID=-1 WHERE GAME_ID=p_game_id;
END;
