DELIMITER $$

DROP FUNCTION IF EXISTS `CREATE_LEAGUE`$$ 
 
CREATE FUNCTION CREATE_LEAGUE(p_gameID INT, p_div_opp1 INT, p_div_opp2 INT, p_div_opp3 INT) RETURNS INT
    NOT DETERMINISTIC
BEGIN
	DECLARE avgLevel INT;
    DECLARE prize INT;
    DECLARE leagueID INT;
    
    SELECT CEIL(AVG(LEVEL)) INTO avgLevel FROM BB_PLAYERS WHERE GAME_ID=p_gameID AND CURR_TEAM=p_gameID;
    SET prize = avgLevel * 60;
    INSERT INTO BB_LEAGUE(LEAGUE_ID, GAME_ID, WEEKS_COMPLETE, DIV_OPP1, DIV_OPP2, DIV_OPP3, PRIZE) VALUES (NULL, p_gameID, 0, p_div_opp1, p_div_opp2, p_div_opp3, prize);
    SELECT LAST_INSERT_ID() INTO leagueID;
    
    RETURN leagueID;
END;