
CREATE TABLE BB_TEAM_LVL_LOOKUP(
 LEVEL INT NOT NULL PRIMARY KEY,
 EXP INT NOT NULL
);

INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(1, 0);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(2, 15);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(3, 50);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(4, 100);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(5, 160);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(6, 230);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(7, 310);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(8, 400);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(9, 500);
INSERT INTO BB_TEAM_LVL_LOOKUP (LEVEL, EXP) VALUES(10, 650);